### ISSUE TITLE
Make djet compatible with Django 1.10 new-style middleware

### ISSUE THREAD

**Issue by jasisz** [sunscrapers/djet#13]
https://github.com/django/deps/blob/master/final/0005-improved-middleware.rst

**Comment by jasisz** [comment]
Taking care of it in the https://github.com/sunscrapers/djet/pull/14 PR, it works but there are some questions/doubts.

**Comment by mmarksnippety** [comment]
@jasisz Thank you for good code. Your PR has been merged.
